spring.application.name=Auth
server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=${postgresql://tickets_user:Zmkp7hzv7KEt0ijSnjwbzit4HfaWgJkG@dpg-d8d7b6po3t8c73e8sumg-a/usuarios_db_i1rx}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:clave_secreta_temporal_123}
